name: "sharpDox"
url: "http://localhost:4000"

appversion: "0.9.8.4"
appdatede: "April 2014"
appdateen: "April 2014"
appdownloadurl: "https://github.com/Geaz/sharpDox/releases/download/v0.9.8.4/sharpDox.0.9.8.4.zip"